// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Skystone.Infrastructure.Data;

#nullable disable

namespace Skystone.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Skystone.Domain.Entities.Badge", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Criteria")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("IconName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Tier")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Badges");

                    b.HasData(
                        new
                        {
                            Id = new Guid("30000000-0000-0000-0000-000000000001"),
                            Criteria = "first_journal_entry",
                            Description = "Completed your first journal entry. The journey begins.",
                            IconName = "fa-solid fa-pen-nib",
                            Name = "First Reflection",
                            Tier = "Bronze"
                        },
                        new
                        {
                            Id = new Guid("30000000-0000-0000-0000-000000000002"),
                            Criteria = "first_vault_item",
                            Description = "Saved your first moment to the Epiphany Vault.",
                            IconName = "fa-solid fa-box-archive",
                            Name = "Vault Keeper",
                            Tier = "Bronze"
                        },
                        new
                        {
                            Id = new Guid("30000000-0000-0000-0000-000000000003"),
                            Criteria = "first_observation_accepted",
                            Description = "Accepted your first ARLO observation about yourself.",
                            IconName = "fa-solid fa-compass",
                            Name = "Identity Explorer",
                            Tier = "Bronze"
                        },
                        new
                        {
                            Id = new Guid("30000000-0000-0000-0000-000000000004"),
                            Criteria = "first_module_session",
                            Description = "Completed your first guided reflection session.",
                            IconName = "fa-solid fa-map",
                            Name = "Module Pioneer",
                            Tier = "Bronze"
                        },
                        new
                        {
                            Id = new Guid("30000000-0000-0000-0000-000000000005"),
                            Criteria = "onboarding_complete",
                            Description = "Completed the full ARLO onboarding journey.",
                            IconName = "fa-solid fa-star",
                            Name = "Odyssey Begun",
                            Tier = "Bronze"
                        },
                        new
                        {
                            Id = new Guid("30000000-0000-0000-0000-000000000006"),
                            Criteria = "five_reflections_kept",
                            Description = "Had 5 reflections marked as meaningful — ARLO is learning who you are.",
                            IconName = "fa-solid fa-brain",
                            Name = "Pattern Seeker",
                            Tier = "Silver"
                        },
                        new
                        {
                            Id = new Guid("30000000-0000-0000-0000-000000000007"),
                            Criteria = "ten_vault_items",
                            Description = "Built up 10 entries in your Epiphany Vault.",
                            IconName = "fa-solid fa-seedling",
                            Name = "Deep Roots",
                            Tier = "Silver"
                        });
                });

            modelBuilder.Entity("Skystone.Domain.Entities.Companion", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("IconName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Persona")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Companions");

                    b.HasData(
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000001"),
                            Description = "Thoughtful, quiet, and deeply analytical. Helps you connect the dots in your journey.",
                            IconName = "fa-eye",
                            ImageUrl = "https://storage.googleapis.com/uxpilot-auth.appspot.com/63800f5124-78519c3a4de1263b31c8.png",
                            Name = "The Observer",
                            Persona = "observer"
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000002"),
                            Description = "Warm, encouraging, and supportive. Walks alongside you as you explore new ideas.",
                            IconName = "fa-deer",
                            ImageUrl = "https://storage.googleapis.com/uxpilot-auth.appspot.com/d010de51bf-ebd46e3be2ff9fcb84d0.png",
                            Name = "The Guide",
                            Persona = "guide"
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000003"),
                            Description = "Curious, challenging, and perceptive. Pushes you to think deeper about your choices.",
                            IconName = "fa-question",
                            ImageUrl = "https://storage.googleapis.com/uxpilot-auth.appspot.com/3a90bd75e6-278ef2b463c2eb024a68.png",
                            Name = "The Questioner",
                            Persona = "questioner"
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000004"),
                            Description = "Let ARLO choose a companion based on your first few reflections.",
                            IconName = "fa-sparkles",
                            ImageUrl = "",
                            Name = "Surprise Me",
                            Persona = "random"
                        });
                });

            modelBuilder.Entity("Skystone.Domain.Entities.JournalEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("ModuleId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ModuleId");

                    b.HasIndex("UserId");

                    b.ToTable("JournalEntries");
                });

            modelBuilder.Entity("Skystone.Domain.Entities.Module", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("EstimatedHours")
                        .HasColumnType("integer");

                    b.Property<string>("IconName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsLocked")
                        .HasColumnType("boolean");

                    b.Property<string>("LongDescription")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("OrderIndex")
                        .HasColumnType("integer");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Modules");

                    b.HasData(
                        new
                        {
                            Id = new Guid("20000000-0000-0000-0000-000000000001"),
                            Description = "Tuning out the expectations of others to hear your own quiet voice.",
                            EstimatedHours = 12,
                            IconName = "fa-solid fa-eye",
                            IsLocked = false,
                            LongDescription = "Before we can figure out where we're going, we often need to quiet the room. This space is about noticing the expectations placed upon you, and gently setting them aside to hear your own voice.",
                            OrderIndex = 1,
                            Title = "Seeing Clearly in a Noisy World"
                        },
                        new
                        {
                            Id = new Guid("20000000-0000-0000-0000-000000000002"),
                            Description = "Exploring the connection between how you feel and who you are.",
                            EstimatedHours = 15,
                            IconName = "fa-solid fa-heart-pulse",
                            IsLocked = false,
                            LongDescription = "Your body and mind are interconnected in ways that shape every decision you make. This module explores those connections through gentle reflection.",
                            OrderIndex = 2,
                            Title = "Health, Self & Being Human"
                        },
                        new
                        {
                            Id = new Guid("20000000-0000-0000-0000-000000000003"),
                            Description = "Noticing what draws your attention and where you find flow.",
                            EstimatedHours = 10,
                            IconName = "fa-solid fa-compass",
                            IsLocked = true,
                            LongDescription = "What lights you up? What makes time disappear? This module is about recognizing your natural pull toward certain ways of being.",
                            OrderIndex = 3,
                            Title = "Signals of Direction"
                        },
                        new
                        {
                            Id = new Guid("20000000-0000-0000-0000-000000000004"),
                            Description = "Understanding how narrative shapes identity and possibility.",
                            EstimatedHours = 12,
                            IconName = "fa-solid fa-book-open",
                            IsLocked = true,
                            LongDescription = "Every belief you hold about yourself is a story. Some serve you. Some don't. This module is about learning to tell new ones.",
                            OrderIndex = 4,
                            Title = "The Stories We Tell"
                        },
                        new
                        {
                            Id = new Guid("20000000-0000-0000-0000-000000000005"),
                            Description = "Exploring where you come from and how it shapes who you are.",
                            EstimatedHours = 14,
                            IconName = "fa-solid fa-seedling",
                            IsLocked = true,
                            LongDescription = "Our roots inform our values, our habits, our fears, and our strengths. Understanding them helps us choose what to carry forward.",
                            OrderIndex = 5,
                            Title = "Roots & Belonging"
                        },
                        new
                        {
                            Id = new Guid("20000000-0000-0000-0000-000000000006"),
                            Description = "Discovering how your unique gifts serve the world around you.",
                            EstimatedHours = 11,
                            IconName = "fa-solid fa-hands-holding-heart",
                            IsLocked = true,
                            LongDescription = "What do you give freely? What comes naturally that others find difficult? This module connects your strengths to purpose.",
                            OrderIndex = 6,
                            Title = "The Art of Contribution"
                        },
                        new
                        {
                            Id = new Guid("20000000-0000-0000-0000-000000000007"),
                            Description = "Building resilience for the moments when the map runs out.",
                            EstimatedHours = 13,
                            IconName = "fa-solid fa-map",
                            IsLocked = true,
                            LongDescription = "Life is full of thresholds where the old maps stop working. This module builds your capacity to be with not-knowing.",
                            OrderIndex = 7,
                            Title = "Navigating Uncertainty"
                        },
                        new
                        {
                            Id = new Guid("20000000-0000-0000-0000-000000000008"),
                            Description = "Imagining and stepping toward who you are becoming.",
                            EstimatedHours = 16,
                            IconName = "fa-solid fa-star",
                            IsLocked = true,
                            LongDescription = "This final module brings everything together — your values, your strengths, your stories — into a vision of who you are becoming.",
                            OrderIndex = 8,
                            Title = "Your Emerging Future"
                        });
                });

            modelBuilder.Entity("Skystone.Domain.Entities.MoodLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date");

                    b.Property<int?>("EnergyScore")
                        .HasColumnType("integer");

                    b.Property<int?>("MoodScore")
                        .HasColumnType("integer");

                    b.Property<bool>("Skipped")
                        .HasColumnType("boolean");

                    b.Property<int?>("SleepScore")
                        .HasColumnType("integer");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId", "Date")
                        .IsUnique();

                    b.ToTable("MoodLogs");
                });

            modelBuilder.Entity("Skystone.Domain.Entities.Observation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Observations");
                });

            modelBuilder.Entity("Skystone.Domain.Entities.PrivacySettings", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("AllowEducatorSummaries")
                        .HasColumnType("boolean");

                    b.Property<bool>("AllowEpiphanyAutoSave")
                        .HasColumnType("boolean");

                    b.Property<bool>("AllowMicrophone")
                        .HasColumnType("boolean");

                    b.Property<bool>("AllowPatternRecognition")
                        .HasColumnType("boolean");

                    b.Property<bool>("HearArloSpeak")
                        .HasColumnType("boolean");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("PrivacySettings");
                });

            modelBuilder.Entity("Skystone.Domain.Entities.Reflection", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ArloText")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("FollowUpQuestion")
                        .HasColumnType("text");

                    b.Property<Guid>("JournalEntryId")
                        .HasColumnType("uuid");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("JournalEntryId");

                    b.ToTable("Reflections");
                });

            modelBuilder.Entity("Skystone.Domain.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("CompanionId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("OnboardingComplete")
                        .HasColumnType("boolean");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("CompanionId");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Skystone.Domain.Entities.UserBadge", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("AwardedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("BadgeId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("BadgeId");

                    b.HasIndex("UserId", "BadgeId")
                        .IsUnique();

                    b.ToTable("UserBadges");
                });

            modelBuilder.Entity("Skystone.Domain.Entities.VaultItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ArloQuote")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("ModuleId")
                        .HasColumnType("uuid");

                    b.Property<string>("Tag")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<string>("UserNote")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ModuleId");

                    b.HasIndex("UserId");

                    b.ToTable("VaultItems");
                });

            modelBuilder.Entity("Skystone.Domain.Entities.JournalEntry", b =>
                {
                    b.HasOne("Skystone.Domain.Entities.Module", "Module")
                        .WithMany("JournalEntries")
                        .HasForeignKey("ModuleId");

                    b.HasOne("Skystone.Domain.Entities.User", "User")
                        .WithMany("JournalEntries")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Module");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Skystone.Domain.Entities.MoodLog", b =>
                {
                    b.HasOne("Skystone.Domain.Entities.User", "User")
                        .WithMany("MoodLogs")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Skystone.Domain.Entities.Observation", b =>
                {
                    b.HasOne("Skystone.Domain.Entities.User", "User")
                        .WithMany("Observations")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Skystone.Domain.Entities.PrivacySettings", b =>
                {
                    b.HasOne("Skystone.Domain.Entities.User", "User")
                        .WithOne("PrivacySettings")
                        .HasForeignKey("Skystone.Domain.Entities.PrivacySettings", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Skystone.Domain.Entities.Reflection", b =>
                {
                    b.HasOne("Skystone.Domain.Entities.JournalEntry", "JournalEntry")
                        .WithMany("Reflections")
                        .HasForeignKey("JournalEntryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("JournalEntry");
                });

            modelBuilder.Entity("Skystone.Domain.Entities.User", b =>
                {
                    b.HasOne("Skystone.Domain.Entities.Companion", "Companion")
                        .WithMany()
                        .HasForeignKey("CompanionId");

                    b.Navigation("Companion");
                });

            modelBuilder.Entity("Skystone.Domain.Entities.UserBadge", b =>
                {
                    b.HasOne("Skystone.Domain.Entities.Badge", "Badge")
                        .WithMany("UserBadges")
                        .HasForeignKey("BadgeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Skystone.Domain.Entities.User", "User")
                        .WithMany("UserBadges")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Badge");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Skystone.Domain.Entities.VaultItem", b =>
                {
                    b.HasOne("Skystone.Domain.Entities.Module", "Module")
                        .WithMany()
                        .HasForeignKey("ModuleId");

                    b.HasOne("Skystone.Domain.Entities.User", "User")
                        .WithMany("VaultItems")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Module");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Skystone.Domain.Entities.Badge", b =>
                {
                    b.Navigation("UserBadges");
                });

            modelBuilder.Entity("Skystone.Domain.Entities.JournalEntry", b =>
                {
                    b.Navigation("Reflections");
                });

            modelBuilder.Entity("Skystone.Domain.Entities.Module", b =>
                {
                    b.Navigation("JournalEntries");
                });

            modelBuilder.Entity("Skystone.Domain.Entities.User", b =>
                {
                    b.Navigation("JournalEntries");

                    b.Navigation("MoodLogs");

                    b.Navigation("Observations");

                    b.Navigation("PrivacySettings");

                    b.Navigation("UserBadges");

                    b.Navigation("VaultItems");
                });
#pragma warning restore 612, 618
        }
    }
}
