import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./styles/main.css";
import Sidebar from "./(components)/sidebar";
import Topbar from "./(components)/topbar";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <div className={`app-shell ${true ? 'loaded' : ''}`}>
          <Sidebar />
          <main className="main">
            <Topbar />
            <div className="main-body">
              {children}
            </div>
          </main>
                  
          
        </div>
        
      </body>
    </html>
  );
}
